import type { Metadata } from 'next'
import { Comic_Relief } from 'next/font/google'
import './globals.css'

const comicRelief = Comic_Relief({
    weight: ['400', '700'],
    subsets: ['latin'],
    fallback: ['Arial', 'sans-serif'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${comicRelief.className} antialiased dark`}>
                {children}
            </body>
        </html>
    )
}
