import type { Metadata } from 'next'
import { Carattere, Comic_Relief, Emilys_Candy } from 'next/font/google'
import './globals.css'
import { I18nProvider } from '@/components/I18nProvider'

// const comicRelief = Comic_Relief({
//     weight: ['400', '700'],
//     subsets: ['latin'],
//     fallback: ['Arial', 'sans-serif'],
// })

const emilysCandy = Emilys_Candy({
    weight: ['400'],
    subsets: ['latin'],
    fallback: ['sans-serif'],
})

export const carattere = Carattere({
    weight: ['400'],
    subsets: ['latin'],
    fallback: ['Comic_Relief', 'Arial', 'sans-serif'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${emilysCandy.className} antialiased dark`}>
                <I18nProvider>{children}</I18nProvider>
            </body>
        </html>
    )
}
